name: publish-rc

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_ADMIN_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alercebroker'
      - name: Install
        run: |
          npm ci
          npx lerna bootstrap
      - name: Version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
        run: |
          git config --global user.name "@dirodriguezm"
          git config --global user.email "dirodriguezm@users.noreply.github.com"
          npx lerna version --conventional-commits --conventional-prerelease --preid rc --yes
          npx lerna publish from-git --registry https://npm.pkg.github.com --yes
      - name: Deploy docs
        env:
          AWS_ACCESS_KEY_ID: "{{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "{{ secrets.AWS_SECREC_ACCESS_KEY }}"
          HTTP_CLIENT_BUCKET_NAME: "{{ secrets.HTTP_CLIENT_BUCKET_NAME }}"
          COMPONENT_LIBRARY_BUCKET_NAME: "{{ secrets.COMPONENT_LIBRARY_BUCKET_NAME }}"
        run: |
          npx lerna run docs:deploy --since
      - name: Deploy apps
        env:
          AWS_ACCESS_KEY_ID: "{{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "{{ secrets.AWS_SECREC_ACCESS_KEY }}"
          EXPLORER_BUCKET_NAME: "{{ secrets.EXPLORER_BUCKET_NAME }}"
        run: |
          npx lerna run deploy --since
