name: publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - feature/trigger-ci

jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alercebroker'
      - name: Install
        run: |
          npm ci
          npx lerna bootstrap
      - name: Version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npx lerna version --conventional-commits --conventional-prerelease --preid rc --yes
          npx lerna publish from-git --registry https://npm.pkg.github.com --yes
