name: unittest

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - './.github/workflows/publish.yaml'
      - '**/docs/**'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap
      - name: Run tests
        run: |
          npx lerna run test:unit --since -- --run
